metadata:
	output_dir: output_results
	sample_annotation: table_experiments_RNA.csv

derived_columns: [data_source]

data_sources:
	source1: /Users/AG/Documents/Github/DESeq-Packager/expr_tsv/RNA_EWS-FLI1_{ews_fli1}_rep{rep}.tsv