metadata:
  sample_annotation: table_experiments_RNA.csv

derived_columns: [data_source]
bioconductor:
  read_fun_name: parseEncodeRegions
data_sources:
  source1: "./expr_tsv/RNA_EWS-FLI1_{ews_fli1}_{treatment_drug}_rep{rep}.tsv"
