metadata:
  sample_annotation: table_experiments_RNA.csv

bioconductor:
  read_fun_name: DESeq_Packager
  read_fun_path: DESeq-Packager.R

derived_columns: [data_source]

data_sources:
  source1: "./expr_tsv/RNA_EWS-FLI1_{ews_fli1}_{treatment_drug}_rep{rep}.tsv"
