metadata:
  sample_annotation: table_experiments_RNA.csv

bioconductor:
  readFunName: DESeqPackager
  readFunPath: DESeqPackager.R
  funcArgs:
    data_source: data_source
    gene_names: ensembl_gene_id
    gene_counts: FPKM

derived_columns: [data_source]

data_sources:
  source1: "./expr_tsv/RNA_EWS-FLI1_{ews_fli1}_{treatment_drug}_rep{rep}.tsv"
