derived_columns: [data_source]

data_sources:
  source1: "~/Documents/DESeq-Packager/expr_tsv/RNA_EWS-FLI1_{ews_fli1}_{treatment_drug}_rep{rep}.tsv"
  #using variable name:
  #${PROCESSED}/...../RNA_EWS-FLI1_{ews_fli1}_rep{rep}.tsv

metadata:
  output_dir: ~/Documents/DESeq-Packager/output_results
  sample_annotation: ~/Documents/DESeq-Packager/table_experiments_RNA.csv
